### ISSUE TITLE
Error: No default engine was specified and no extension was provided.

### ISSUE THREAD

**Issue by dvision1979** [deluxor/nodejs-nginx-rtmp-balancer#3]
When trying to use the API to get the list of servers/freeservers all I get is:
`Error: No default engine was specified and no extension was provided.<br> &nbsp; &nbsp;at new View (/usr/local/receiver/node_modules/express/lib/view.js:48:42)<br> &nbsp; &nbsp;at Function.app.render (/usr/local/receiver/node_modules/express/lib/application.js:545:12)<br> &nbsp; &nbsp;at ServerResponse.res.render (/usr/local/receiver/node_modules/express/lib/response.js:938:7)<br> &nbsp; &nbsp;at /usr/local/receiver/app.js:82:9<br> &nbsp; &nbsp;at Layer.handle_error (/usr/local/receiver/node_modules/express/lib/router/layer.js:58:5)<br> &nbsp; &nbsp;at trim_prefix (/usr/local/receiver/node_modules/express/lib/router/index.js:300:13)<br> &nbsp; &nbsp;at /usr/local/receiver/node_modules/express/lib/router/index.js:270:7<br> &nbsp; &nbsp;at Function.proto.process_params (/usr/local/receiver/node_modules/express/lib/router/index.js:321:12)<br> &nbsp; &nbsp;at next (/usr/local/receiver/node_modules/express/lib/router/index.js:261:10)<br> &nbsp; &nbsp;at Layer.handle_error (/usr/local/receiver/node_modules/express/lib/router/layer.js:60:5)`

I am calling http://172.16.1.232:3030/caller/servers.

My receiver config is:
`{
  "_comment": "Please update the parameters below with your own ones",
  "port": 3030,
  "key": "1e06725f825882d0636caa877c1bcf368c8fabad",
  "timeout": 5000
}`

... and the caller config:
`{
  "_comment": "Please update the parameters below with your own ones",
  "edge_address": "172.16.1.222",
  "edge_stats_address": "172.16.1.222",
  "edge_stats_port": 80,
  "path": "/lb",
  "timer": 1000,
  "load_balancer_address": "172.16.1.232",
  "load_balancer_port": 3030,
  "load_balancer_key": "1e06725f825882d0636caa877c1bcf368c8fabad"
}`

Am I doing something wrong?

**Comment by sriman** [comment]
Me too faced the same issue.

See the route of the file, it will be /servers

Call _http://<your_ip>:<your port>/servers_  instead of _http://<your_ip>:<your port>/caller/servers_ as mentioned in this video https://www.youtube.com/watch?v=cGJlcR3Qf9A&feature=youtu.be
